"""esquema completo de SPEC 7

Revision ID: bee7093fc188
Revises: 
Create Date: 2026-08-26 22:56:12.020711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee7093fc188'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin')", name=op.f('ck_admin_users_role_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    op.create_table('people',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people'))
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_display_name'), ['display_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_people_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('access_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('person_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_access_tokens_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_tokens'))
    )
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_tokens_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name=op.f('ck_documents_status_valido')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('project_id', 'path', name='uq_documents_project_path')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_documents_project_path', ['project_id', 'path'], unique=False)

    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('person_id', sa.String(length=40), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_project_members_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'person_id', name=op.f('pk_project_members'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('person_id', sa.String(length=40), nullable=False),
    sa.Column('role_label', sa.String(length=64), nullable=False),
    sa.Column('session_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_metadata', sa.JSON(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'stale', 'closed')", name=op.f('ck_sessions_status_valido')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_sessions_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sessions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_sessions_project_person_role', ['project_id', 'person_id', 'role_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_session_key'), ['session_key'], unique=True)

    op.create_table('threads',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'resolved')", name=op.f('ck_threads_status_valido')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_threads_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads'))
    )
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_project_id'), ['project_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('author_address', sa.String(length=130), nullable=False),
    sa.Column('author_session_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("intent IN ('create', 'append', 'amend', 'deprecate')", name=op.f('ck_document_versions_intent_valido')),
    sa.ForeignKeyConstraint(['author_session_id'], ['sessions.id'], name=op.f('fk_document_versions_author_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_versions_doc_version')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('thread_id', sa.String(length=40), nullable=False),
    sa.Column('in_reply_to', sa.String(length=40), nullable=True),
    sa.Column('sender_session_id', sa.String(length=40), nullable=True),
    sa.Column('sender_address', sa.String(length=130), nullable=False),
    sa.Column('recipient_address', sa.String(length=130), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claimed_by_session_id', sa.String(length=40), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('question', 'answer', 'notice', 'proposal', 'agreement')", name=op.f('ck_messages_kind_valido')),
    sa.CheckConstraint("status IN ('pending', 'delivered', 'in_progress', 'answered', 'unclaimed')", name=op.f('ck_messages_status_valido')),
    sa.ForeignKeyConstraint(['claimed_by_session_id'], ['sessions.id'], name=op.f('fk_messages_claimed_by_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['in_reply_to'], ['messages.id'], name=op.f('fk_messages_in_reply_to_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_messages_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_session_id'], ['sessions.id'], name=op.f('fk_messages_sender_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_messages_thread_id_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_in_reply_to'), ['in_reply_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_messages_project_recipient_status', ['project_id', 'recipient_address', 'status'], unique=False)
        batch_op.create_index('ix_messages_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('message_deliveries',
    sa.Column('message_id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_deliveries_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_message_deliveries_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'session_id', name=op.f('pk_message_deliveries'))
    )
    op.create_table('message_dismissals',
    sa.Column('message_id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_dismissals_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_message_dismissals_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'session_id', name=op.f('pk_message_dismissals'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_dismissals')
    op.drop_table('message_deliveries')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_thread_id'))
        batch_op.drop_index('ix_messages_project_status')
        batch_op.drop_index('ix_messages_project_recipient_status')
        batch_op.drop_index(batch_op.f('ix_messages_project_id'))
        batch_op.drop_index(batch_op.f('ix_messages_in_reply_to'))

    op.drop_table('messages')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_project_id'))

    op.drop_table('threads')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_session_key'))
        batch_op.drop_index('ix_sessions_project_person_role')
        batch_op.drop_index(batch_op.f('ix_sessions_project_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_person_id'))

    op.drop_table('sessions')
    op.drop_table('project_members')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_project_path')
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))

    op.drop_table('documents')
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_access_tokens_person_id'))

    op.drop_table('access_tokens')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))

    op.drop_table('projects')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_email'))
        batch_op.drop_index(batch_op.f('ix_people_display_name'))

    op.drop_table('people')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
